postgres_admin_password: password
postgres_new_database: new_database
postgres_new_database_users_granted: [postgres]
postgres_new_user: kek
postgres_new_user_password: lol
postgres_new_user_database: postgres
postgres_new_user_granted_databases: [postgres, new_database]